### ISSUE TITLE
poll member names with & (ampersand) in it problem

### ISSUE THREAD

**Issue by himbeere** [kellerben/dudle#61] opened 2017-01-08 19:24 UTC
Hello.

From time to time i have poll members named "Tim & Struppi" for example. It's not possible to edit or delete those entries. Is that a known issue?

thanks and cheers

**Comment by kellerben** [comment] 2017-01-08 20:06
Can you send me a link to the issue? This problem sounds like #16 and was fixed here 50e5dbbf4b6fd1593396437ef05d8e6902c0f17c

**Comment by himbeere** [comment] 2017-01-08 20:09
Here is the link: https://dudle.lordcritical.de/github/

Try to delete or edit the "Tim & Struppi" line.

Thanks for looking at it.

cheers

**Comment by kellerben** [comment] 2017-01-08 21:57
As I thought, this bug is fixed in 50e5dbb, you need to update the server to the current software version.
Duplicate of #16

**Closed by kellerben** 2017-01-08 21:57 UTC
Labels: bug, duplicate

**Comment by himbeere** [comment] 2017-01-09 08:01
And by current software you mean git master?

thanks and cheers

**Comment by kellerben** [comment] 2017-01-09 10:07
Yes. At least the commit I mentioned above.

**Comment by himbeere** [comment] 2017-01-09 10:08
ok. thanks.

**Comment by himbeere** [comment] 2017-01-12 10:32
Confirmed. Problem solved.
